/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: c73e10ca2457f41f867107f22fedbd64)
declare namespace Cloudflare {
	interface Env {
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		AI: Ai;
		TRELLO_API_KEY?: string;
		TRELLO_TOKEN?: string;
		TRELLO_BOARD_ID?: string;
		TRELLO_BOARD_NAME?: string;
	}
}
interface Env extends Cloudflare.Env {}
